language: php

env:
  - SILEX_VERSION="~2.0@dev"

before_script:
  - travis_retry composer require silex/silex:${SILEX_VERSION}
  - travis_retry composer install --dev --prefer-source

script: vendor/bin/phpunit

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
  allow_failures:
      - php: hhvm
